"""empty message

Revision ID: 7ccca82fab49
Revises: 
Create Date: 2024-01-31 18:14:45.443021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccca82fab49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=50), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parfum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateur_categories',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'categorie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur_categories')
    op.drop_table('parfum')
    op.drop_table('commande')
    op.drop_table('utilisateur')
    op.drop_table('categorie')
    # ### end Alembic commands ###
